version: '3.7'

services:
  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY='yourJWTkey'
      - DEMO=1
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=http://localhost
    ports:
      - "80:80"